setopt extendedglob
setopt menucomplete
setopt AUTO_CD
setopt AUTO_PUSHD PUSHD_IGNORE_DUPS PUSHD_TO_HOME
setopt alwaystoend
unsetopt HIST_IGNORE_ALL_DUPS HIST_SAVE_NO_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_FCNTL_LOCK
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
unsetopt ALL_EXPORT
setopt LONG_LIST_JOBS
setopt AUTO_RESUME
setopt NOTIFY
unsetopt BG_NICE
unsetopt HUP
unsetopt CHECK_JOBS
unsetopt CORRECT_ALL
unsetopt FLOW_CONTROL
setopt INTERACTIVE_COMMENTS
setopt PRINT_EXIT_VALUE
setopt PROMPT_SUBST
setopt MAGIC_EQUAL_SUBST
unsetopt MULTIOS
setopt BSD_ECHO


