k9s:
  refreshRate: 2
  headless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    fullScreenLogs: false
    textWrap: false
    showTime: true
  currentContext: local
  currentCluster: local
  clusters:
    local:
      namespace:
        active: default
        favorites:
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
