k9s:
  refreshRate: 2
  headless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: kubernetes-admin@ks.rwxrwxrwx.dev
  currentCluster: ks.rwxrwxrwx.dev
  clusters:
    ks.rwxrwxrwx.dev:
      namespace:
        active: default
        favorites:
        - default
      view:
        active: svc
      featureGates:
        nodeShell: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
