---

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

extends: default

# https://yamllint.readthedocs.io/en/stable/rules.html
rules:
  braces:
    level: warning
    max-spaces-inside: 1
  brackets:
    level: warning
    max-spaces-inside: 1
  colons:
    level: warning
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1
    level: warning
  comments:
    require-starting-space: true
    min-spaces-from-content: 2
    level: warning
  comments-indentation: disable
  document-end: disable
  document-start: disable
  empty-lines:
    max: 1
    level: warning
  empty-values:
    level: warning
  hyphens:
    level: warning
  indentation:
    spaces: consistent
    indent-sequences: consistent
    level: warning
  key-duplicates:
    level: warning
  line-length:
    max: 100
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
    level: warning
  new-line-at-end-of-file:
    level: warning
  new-lines:
    type: unix
    level: warning
  octal-values:
    forbid-implicit-octal: true
    level: warning
  quoted-strings: disable
  trailing-spaces:
    level: warning
  truthy:
    level: warning
