# # Don't print a new line at the start of the prompt
# add_newline = true

# # Replace the "❯" symbol in the prompt with "➜"
# [character]
# symbol = "❯"
# error_symbol = "✗"
# use_symbol_for_status = false
# style_success = "fg:#6c6cd2"
# style_failure = "underline fg:#9c27b0"

# # Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

# # Wait 10 milliseconds for starship to check files under the current directory.
# # scan_timeout = 10

# [battery]
# disabled = true

# [directory]
# truncation_length = 3
# truncate_to_repo = true
# use_logical_path = true
# fish_style_pwd_dir_length	= 3
# style = "#80cbc4"

# [dotnet]
# disabled = true

# [env_var]
# symbol = "➜"
# variable = "SSH_AGENT_ID"
# # default = ""
# # style	= "dimmed black"
# style = "#80cbc4"

# prompt_order = [
#     "username",
#     "hostname",
#     "kubernetes",
#     "directory",
#     "git_branch",
#     "git_state",
#     "git_status",
#     "hg_branch",
#     "package",
#     "dotnet",
#     "golang",
#     "java",
#     "nodejs",
#     "python",
#     "ruby",
#     "rust",
#     "nix_shell",
#     "conda",
#     "memory_usage",
#     "aws",
#     "env_var",
#     "cmd_duration",
#     "line_break",
#     "jobs",
#     "battery",
#     "time",
#     "character",
# ]

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
scan_timeout = 50

format = """
$username\
$hostname\
$status\
$shell\
$directory\
$kubernetes\
$docker_context\
$git_branch\
$git_commit\
$git_metrics\
$git_status\
$jobs\
$character"""

[character]
format = "$symbol$symbol "
success_symbol = "[❯](bold fg:#6c6cd2)"
error_symbol = "[❯](bold fg:#d87b64)"

[hostname]
ssh_only = false
format = "[$hostname](bold dimmed fg:#d292e3) "
trim_at = ".companyname.com"
disabled = false

[directory]
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
use_logical_path = false
# fish_style_pwd_dir_length	= 3
read_only = "🔒"
read_only_style = "red"
repo_root_style = "#34ef6f"
style = "#87abe6"
format = "[$path]($style)[$read_only]($read_only_style) "

# [directory.substitutions]
# "/Volumes/network/path" = "/net"
# "src/com/long/java/path" = "mypath"

[jobs]
symbol = "✦ "
symbol_threshold = 1
number_threshold = 2
format = "[$symbol$number](bold fg:#5564e8) "

[docker_context]
symbol = "🐋"
style = "blue bold"
format = "[$symbol$context]($style) "

[kubernetes]
symbol = "☸"
format = '[$symbol $context(|$namespace)](dimmed fg:#8a5eeb) '
disabled = false
[kubernetes.context_aliases]
".*.local.cluster.k8s" = "dev"
# "gke_.*_(?P<var_cluster>[\\w-]+)" = "gke-$var_cluster"

[helm]
version_format = "v${raw}"
symbol = "⛵ "
format = "[$symbol](bold fg:#b5c1c4) "

[git_branch]
always_show_remote = false
only_attached = false
truncation_length = 5
truncation_symbol = ".."
ignore_branches = ["master", "main"]
symbol = " "
# symbol = "🌱 "
format = "[$symbol](fg:#87abe6)[$branch(:$remote_branch)](bold purple) "
disabled = true

[git_metrics]
format = '[+$added](fg:#346591)/[-$deleted](fg:#d77aac) '
disabled = true

[git_status]
conflicted = "🏳"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
up_to_date = "✓"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
format = '([\[$all_status$ahead_behind\]](fg:#d77aa9) )'
disabled = true

# [env_var.SSH_AGENT_ID]
# symbol = "🤖"
# default = ""
# format = "$symbol:[$env_value]($style)"

# default format
# format = """
# $username\
# $hostname\
# $localip\
# $shlvl\
# $singularity\
# $kubernetes\
# $directory\
# $vcsh\
# $git_branch\
# $git_commit\
# $git_state\
# $git_metrics\
# $git_status\
# $hg_branch\
# $docker_context\
# $package\
# $buf\
# $c\
# $cmake\
# $cobol\
# $container\
# $dart\
# $deno\
# $dotnet\
# $elixir\
# $elm\
# $erlang\
# $golang\
# $haskell\
# $helm\
# $java\
# $julia\
# $kotlin\
# $lua\
# $nim\
# $nodejs\
# $ocaml\
# $perl\
# $php\
# $pulumi\
# $purescript\
# $python\
# $rlang\
# $red\
# $ruby\
# $rust\
# $scala\
# $swift\
# $terraform\
# $vlang\
# $vagrant\
# $zig\
# $nix_shell\
# $conda\
# $spack\
# $memory_usage\
# $aws\
# $gcloud\
# $openstack\
# $azure\
# $env_var\
# $crystal\
# $custom\
# $sudo\
# $cmd_duration\
# $line_break\
# $jobs\
# $battery\
# $time\
# $status\
# $shell\
# $character"""