# NOTE: https://starship.rs/config

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
scan_timeout = 50

format = """
$username\
$hostname\
$directory\
$jobs\
$character"""

right_format = """
$kubernetes\
$docker_context\
$helm\
$git_branch\
$git_commit\
$git_metrics\
$git_status"""

[username]
style_user = "fg:#97e3e0"
format = "[$user]($style)"
show_always = true
disabled = true

[character]
format = "$symbol$symbol "
success_symbol = "[❯](bold fg:#6c6cd2)"
error_symbol = "[❯](bold fg:#d87b64)"

[hostname]
ssh_only = false
format = "[@](bold fg:#7f55a6)[$hostname](bold fg:#d459d1) "
disabled = false

[directory]
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
use_logical_path = false
# fish_style_pwd_dir_length	= 3
read_only = "🔒"
read_only_style = "red"
repo_root_style = "#34ef6f"
style = "#87abe6"
format = "[$path]($style)[$read_only]($read_only_style) "

# [directory.substitutions]
# "/Volumes/network/path" = "/net"
# "src/com/long/java/path" = "mypath"

[jobs]
symbol = "✦"
symbol_threshold = 1
number_threshold = 2
format = "[$symbol$number](bold fg:#5564e8) "

[docker_context]
symbol = "🐋"
style = "blue bold"
format = "[$symbol$context]($style) "

[kubernetes]
symbol = "☸"
format = '[$symbol $context(|$namespace)](fg:#dcc1ad) '
disabled = true
[kubernetes.context_aliases]
".*.local.cluster.k8s" = "dev"
# "gke_.*_(?P<var_cluster>[\\w-]+)" = "gke-$var_cluster"

[helm]
version_format = "v${raw}"
symbol = "⛵ "
format = "[$symbol](bold fg:#b5c1c4) "

[git_branch]
always_show_remote = false
only_attached = false
truncation_length = 5
truncation_symbol = ".."
ignore_branches = ["master", "main"]
symbol = " "
# symbol = "🌱 "
format = "[$symbol](fg:#87abe6)[$branch(:$remote_branch)](bold purple) "
disabled = true

[git_metrics]
format = '[+$added](fg:#346591)/[-$deleted](fg:#d77aac) '
disabled = true

[git_status]
conflicted = "🏳"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
up_to_date = "✓"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
format = '([\[$all_status$ahead_behind\]](fg:#d77aa9) )'
disabled = true

# [env_var.SSH_AGENT_ID]
# symbol = "🤖"
# default = ""
# format = "$symbol:[$env_value]($style)"
